apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: tickers-app
manifests:
  rawYaml:
    - infra/k8s/*
    - infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: iandrew/auth
      context: .
      docker:
        dockerfile: ./auth/Dockerfile
      sync:
        manual:
          - src: 'auth/src/**/*.ts'
            dest: .
          - src: 'packages/server/**/*.ts'
            dest: .
          - src: 'packages/common/**/*.ts'
            dest: .
    - image: iandrew/client
      context: client
      docker:
        dockerfile: DockerfileDev
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.ts'
            dest: .
          - src: '**/*.tsx'
            dest: .
    - image: iandrew/mail
      context: mail
      docker:
        dockerfile: DockerfileDev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: iandrew/assets
      context: .
      docker:
        dockerfile: ./assets/Dockerfile
      sync:
        manual:
          - src: 'assets/src/**/*.ts'
            dest: .
          - src: 'packages/server/**/*.ts'
            dest: .

profiles:
  - name: development
    build:
      artifacts:
        - image: iandrew/auth
          docker:
            dockerfile: ./auth/Dockerfile
            buildArgs:
              NODE_ENV: "development"
  - name: development
    build:
      artifacts:
        - image: iandrew/assets
          docker:
            dockerfile: ./assets/Dockerfile
            buildArgs:
              NODE_ENV: "development"


