apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: tickers-app
manifests:
  rawYaml:
    - infra/k8s/*
    - infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: iandrew/auth
      context: .
      docker:
        dockerfile: ./auth/Dockerfile
      sync:
        manual:
          - src: './auth/src/**/*.ts'
            dest: './auth/src'
          - src: './packages/server/**/*.ts'
            dest: './packages/server'
          - src: './packages/common/**/*.ts'
            dest: './packages/common'
    - image: iandrew/client
      context: .
      docker:
        dockerfile: ./client/Dockerfile
      sync:
        manual:
          - src: './client/**/*.js'
            dest: .
          - src: './client/**/*.ts'
            dest: .
          - src: './client/**/*.tsx'
            dest: .
          - src: './packages/common/**/*.ts'
            dest: './packages/common'
    - image: iandrew/mail
      context: .
      docker:
        dockerfile: ./mail/Dockerfile
      sync:
        manual:
          - src: './mail/src/**/*.ts'
            dest: './mail/src'
          - src: './packages/server/**/*.ts'
            dest: './packages/server'
          - src: './packages/common/**/*.ts'
            dest: './packages/common'
    - image: iandrew/assets
      context: .
      docker:
        dockerfile: ./assets/Dockerfile
      sync:
        manual:
          - src: './assets/src/**/*.ts'
            dest: './assets/src'
          - src: './packages/server/**/*.ts'
            dest: './packages/server'
          - src: './packages/common/**/*.ts'
            dest: './packages/common'

profiles:
  - name: development
    build:
      artifacts:
        - image: iandrew/auth
          docker:
            dockerfile: ./auth/Dockerfile
            buildArgs:
              NODE_ENV: "development"
  - name: development
    build:
      artifacts:
        - image: iandrew/assets
          docker:
            dockerfile: ./assets/Dockerfile
            buildArgs:
              NODE_ENV: "development"
  - name: development
    build:
      artifacts:
        - image: iandrew/mail
          docker:
            dockerfile: ./mail/Dockerfile
            buildArgs:
              NODE_ENV: "development"


