apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: tickers-app
manifests:
  rawYaml:
    - infra/k8s/*
    - infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: iandrew/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.ts'
            dest: .
          - src: '**/*.tsx'
            dest: .



