name: Install dependencies in web-app/ services
description: Install dependencies in web-app/ services

inputs:
  npm-token:
    description: NPM token
    required: true
  github-workspace:
    description: Github workspace
    required: true
  service-name:
    description: Service name
    required: true

runs:
  using: composite
  steps:

    # Create .npmrc
    - name: Create .npmrc
      run: |
        echo 'registry=https://registry.npmjs.org/' >> ${{ inputs.github-workspace }}/web-app/${{ inputs.service-name }}/.npmrc
        echo 'https://registry.npmjs.org/:_authToken=${{ inputs.npm-token  }}' >> ${{ inputs.github-workspace }}/web-app/${{ inputs.service-name }}/.npmrc
      shell: bash

    # Run ls
    - run: ls -la ${{ inputs.github-workspace }}/web-app/${{ inputs.service-name }}/
      shell: bash


    # Install your dependencies
    - run: npm ci --prefix ./web-app/${{ inputs.service-name }}/
      shell: bash
