name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - 'packages/common/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker build --build-arg NODE_ENV=production WEB_APP_DOMAIN=${{ secrets.WEB_APP_DOMAIN  }} --target production -f ./client/Dockerfile -t iandrew/client .        # build new image of client
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD # login to docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push iandrew/client                           # push new built image to docker hub
      - uses: digitalocean/action-doctl@v2                        # deploy image to digital ocean cluster
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticker-app-cluster # kubeconfig name "tickers-app" get from digital ocean cluster
      - run: kubectl rollout restart deployment client-depl       # restart client deployment "client-depl" name getting from infra/k8s/client-depl.yaml file
