name: deploy-assets

on:
  push:
    branches:
      - main
    paths:
      - 'assets/**'
      - 'packages/common/**'
      - 'packages/server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --build-arg NODE_ENV=production --target production -f ./assets/Dockerfile -t iandrew/assets .        # build new image of assets
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD # login to docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push iandrew/assets                           # push new built image to docker hub
      - uses: digitalocean/action-doctl@v2                        # deploy image to digital ocean cluster
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticker-app-cluster # kubeconfig name "tickers-app" get from digital ocean cluster
      - run: kubectl rollout restart deployment assets-depl       # restart assets deployment "assets-depl" name getting from infra/k8s/assets-depl.yaml file
