name: Check web-app/container service on Pull Requests

on:
  pull_request:
    paths:
      - 'web-app/container/**'

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Setup environment
      - name: Setup environment
        uses: ./.github/actions/setup_env
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-workspace: ${{ github.workspace }}

      # Run ESLint
      - name: Run ESLint for web-app/container service
        run:  npx eslint --c .eslintrc.json ./web-app/container/

  build:
    name: Build web-app/container service by webpack
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Setup environment
      - name: Setup environment
        uses: ./.github/actions/setup_env
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-workspace: ${{ github.workspace }}

      # Build service web-app/container
      - name: Run build for web-app/container service by webpack
        run: npm run build:web-app/container
