name: Check auth service on Pull Requests

on:
  pull_request:
    paths:
      - 'auth/**'

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Setup environment
      - name: Setup environment
        uses: ./.github/actions/setup_env
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-workspace: ${{ github.workspace }}

      # Run ESLint
      - name: Run ESLint for auth service
        run:  npx eslint --c .eslintrc.json ./auth/

  compilation:
    name: Build auth service by Typescript
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Setup environment
      - name: Setup environment
        uses: ./.github/actions/setup_env
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-workspace: ${{ github.workspace }}

      # install dependencies
      - name: install dependencies
        run: npm ci

      # Build service by Typescript
      - name: Run Typescript build for auth service
        run: npm run build:auth

  test:
    name: Run tests for auth service
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Setup environment
      - name: Setup environment
        uses: ./.github/actions/setup_env
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-workspace: ${{ github.workspace }}

      # install dependencies in auth service
      - name: Install dependencies in auth service
        run: npm ci

      # install @tickers-app/common dependencies // TODO: remove this step after
      - name: install @tickers-app/common dependencies
        run: |
          cd ./auth
          npm install @tickers-app/common

      # Run tests
      - name: Run tests for auth service
        run: npm run test:auth


